# Листинг 2.116
print('Эти данные будут иметь значение - False')
print('bool(None):', bool(None))       
print('bool(0):', bool(0))
print('bool(0.0):', bool(0.0))
print('bool(0+0j):', bool(0+0j))
print('bool(""):', bool(''))
print('bool([]):', bool([]))
print('bool({}):', bool({}))
print('bool(tuple()):', bool(tuple()))
print('bool(dict()):', bool(dict()))
print('--------------------------------------')
print('Эти данные будут иметь значение - True')
print('bool("0"):', bool('0'))
print('bool(-1):', bool(-1))
print('bool([False]):', bool([False]))
print('bool({0,}):', bool({0, }))
print('bool((0,)):', bool((0, )))